# Generated by Django 5.2.6 on 2025-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción del avance')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Ingrese un valor entre 0 y 100', verbose_name='Porcentaje de avance')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('correction', 'Corrección')], default='pending', max_length=20, verbose_name='Estado')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='progress_evidence/', verbose_name='Evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['-created_at'],
            },
        ),
    ]
