# Generated by Django 5.2.6 on 2025-11-20 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress_tracking', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracking',
            name='apprentice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL, verbose_name='Aprendiz'),
        ),
        migrations.AddField(
            model_name='progresstracking',
            name='instructor_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_progress_entries', to=settings.AUTH_USER_MODEL, verbose_name='Instructor revisor'),
        ),
        migrations.AddField(
            model_name='progresstracking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='projects.project', verbose_name='Proyecto'),
        ),
    ]
