# Generated by Django 5.2.6 on 2025-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/', verbose_name='Archivo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('attachment_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagen'), ('archive', 'Archivo comprimido'), ('other', 'Otro')], default='document', max_length=20, verbose_name='Tipo')),
                ('is_public', models.BooleanField(default=False, verbose_name='¿Visible para aprendices?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
