# Generated by Django 5.2.6 on 2025-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('backup_type', models.CharField(choices=[('full', 'Completo'), ('incremental', 'Incremental')], default='full', max_length=20, verbose_name='Tipo de copia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En proceso'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Archivo generado')),
                ('log', models.TextField(blank=True, verbose_name='Registro del proceso')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Copia de seguridad',
                'verbose_name_plural': 'Copias de seguridad',
                'ordering': ['-created_at'],
            },
        ),
    ]
