# Generated by Django 5.2.6 on 2025-11-21 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('assigned_at', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('apprentices', models.ManyToManyField(blank=True, related_name='apprentice_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Aprendices')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
