# Generated by Django 5.2.6 on 2025-11-21 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('instructors', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project', verbose_name='Proyecto'),
        ),
    ]
