# Generated by Django 5.2.6 on 2025-11-20 02:20

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('sector', models.CharField(choices=[('Tecnología', 'Tecnología'), ('Servicios', 'Servicios'), ('Salud', 'Salud'), ('Manufactura', 'Manufactura'), ('Educación', 'Educación'), ('Comercio', 'Comercio'), ('Transporte', 'Transporte'), ('Construcción', 'Construcción'), ('Otro', 'Otro')], default='Tecnología', max_length=50, verbose_name='Sector Empresarial')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_path, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
